<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>FPSOverlay</AssemblyName>
    <Version>3.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FPSOverlay.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.2.3" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="NvAPIWrapper.Net" Version="0.8.1.101" />
    <PackageReference Include="System.Management" Version="10.0.2" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>

    <ItemGroup>
    <Resource Include="app.ico" />
    <Resource Include="Assets\mars-logo.png" />
    <Resource Include="Assets\Fonts\*.ttf" />
    <Content Include="AiOc\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="FPSOverlay.Tests\**" />
    <None Include="FPSOverlay.Tests\**" />
    <EmbeddedResource Remove="FPSOverlay.Tests\**" />
    <Page Remove="FPSOverlay.Tests\**" />
  </ItemGroup>

</Project>
